resource.AddFile("sound/deception/st_2_2.mp3")
resource.AddFile("sound/deception/hbeat.wav")
resource.AddFile("sound/deception/death1.mp3")
resource.AddFile("sound/deception/death2.mp3")
resource.AddFile("materials/altarmor/flak_vest.vmt")
resource.AddFile("materials/altarmor/dyneema_vest.vmt")
resource.AddFile("materials/altarmor/kevlar_bodyarmor.vmt")
resource.AddFile("materials/deception/icon_killtime_2.vmt")
resource.AddFile("materials/deception/icon_playerrole.vmt")
resource.AddFile("materials/deception/icon_killcaliber_2.vmt")
resource.AddFile("materials/deception/money.vmt")
resource.AddFile("materials/deception/adv_help.vmt")
resource.AddFile("particles/cstm_muzzleflashes.pcf")
resource.AddFile("materials/deception/vig_left.vmt")
resource.AddFile("materials/deception/vig_right.vmt")
resource.AddFile("materials/deception/vig_lleft.vmt")
resource.AddFile("materials/deception/vig_lright.vmt")
resource.AddFile("materials/deception/icons/ic_antidote.vmt")
resource.AddFile("materials/deception/icons/ic_radio.vmt")
//resource.AddFile("materials/deception/icons/ic_.vmt")

for i = 1, 6 do
	resource.AddFile("sound/deception/instruc" .. i .. ".mp3")
end